# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 201, 351))
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_workdir = QtWidgets.QAction(MainWindow)
        self.action_open_workdir.setObjectName("action_open_workdir")
        self.action_new_workdir = QtWidgets.QAction(MainWindow)
        self.action_new_workdir.setObjectName("action_new_workdir")
        self.action_U_net = QtWidgets.QAction(MainWindow)
        self.action_U_net.setObjectName("action_U_net")
        self.action_close_workdir = QtWidgets.QAction(MainWindow)
        self.action_close_workdir.setObjectName("action_close_workdir")
        self.menu.addAction(self.action_new_workdir)
        self.menu.addAction(self.action_open_workdir)
        self.menu.addAction(self.action_close_workdir)
        self.menu_3.addAction(self.action_U_net)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.q_action)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "模型"))
        self.action_open_workdir.setText(_translate("MainWindow", "打开工作区"))
        self.action_new_workdir.setText(_translate("MainWindow", "新建工作区"))
        self.action_U_net.setText(_translate("MainWindow", "U-net"))
        self.action_close_workdir.setText(_translate("MainWindow", "关闭工作区"))
