# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modelTab(object):
    def setupUi(self, modelTab):
        modelTab.setObjectName("modelTab")
        modelTab.resize(1005, 629)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        modelTab.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(modelTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(modelTab)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(modelTab)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.comboBox_model = QtWidgets.QComboBox(modelTab)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_model.setFont(font)
        self.comboBox_model.setObjectName("comboBox_model")
        self.horizontalLayout_6.addWidget(self.comboBox_model)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser_model_explaination = QtWidgets.QTextBrowser(modelTab)
        self.textBrowser_model_explaination.setObjectName("textBrowser_model_explaination")
        self.horizontalLayout_2.addWidget(self.textBrowser_model_explaination)
        self.graphicsView = QtWidgets.QGraphicsView(modelTab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_load = QtWidgets.QPushButton(modelTab)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(modelTab)
        self.comboBox_model.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(modelTab)

    def retranslateUi(self, modelTab):
        _translate = QtCore.QCoreApplication.translate
        modelTab.setWindowTitle(_translate("modelTab", "modelTab"))
        self.checkBox.setText(_translate("modelTab", "choose from my model"))
        self.label_10.setText(_translate("modelTab", "Model："))
        self.pushButton_load.setText(_translate("modelTab", "load"))
